### ISSUE TITLE
No docs at all 

### ISSUE THREAD

**Issue by Nereg** [ShyPixie/stlib#9]
Please bring up some docs I really need your library

**Comment by ShyPixie** [comment]
So much work to do alone... but I will keep it open in case of someone willing to help. 

Besides that, I have a skeleton documentation in the repository (/doc) and all functions has type hints, if you compile that you could have a good idea.

**Comment by Nereg** [comment]
OK I will compile docs.

**Comment by Nereg** [comment]
I compiled them. https://drive.google.com/file/d/1qxTYkFAMQHKqdtlCjhwj6nxdzA2chQgu/view?usp=sharing here they are. Not shure if they would be helpfull but I done it

**Comment by ShyPixie** [comment]
fixed
